### PR TITLE
2.2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by daniyalj** [comment]
@roman-in-arctiq Im thinking we'll create two versions of the app and add them to different folders. 1 has a static version and one as a satellite version. Thats my initial thinking. I'll make suggest some changes to the formatting and branding as well.

Also please add a description for your PR

**Comment by ghost** [comment]
I think two versions make sense. This one may be heavier than needed for some.

We can also add version like this, but no map loading. Lighter...

I am not sure how to add description to the PR now. Hope that is OK.

**Comment by daniyalj** [comment]
@roman-in-arctiq can you make two directories for `mountain` and `satellite`? throw the new in satellite and the older in mountain

**Comment by ghost** [comment]
@daniyalj I was using two different map providers: Google Maps and Mapquest. Mapquest being static map image of any type (satellite, map, dark map). Google Maps being dynamic. With the ability to zoom, pan and so on also of any type (satellite, map, dark map).

My main decision is which provider to use. I could use both, Google set by default, Mapquest set by slightly modified URL to call the app.

The last thing is that to run API keys are needed. Currently they are hardcoded and I mine. I would like to change that I pass them at build time.

**Comment by daniyalj** [comment]
Will review sometime this week

**Comment by daniyalj** [comment]
Closing this PR and making the repo into a per branch model for easier deployment and demos

**Pull request closed without merging**
